### ISSUE TITLE
idoitcli init --> api.username" is too short.

### ISSUE THREAD

**Issue by cnu80** [bheisig/i-doit-cli#20]
### Expected behavior

Some simple questions will be asked how to access your i-doit installation.

### Actual behavior
One or more errors found in configuration settings:
Configuration setting "api.username" is too short. Minimum length is 1 character(s).
Configuration setting "api.password" is too short. Minimum length is 1 character(s).
Cannot proceed unless you fix your configuration

### Steps to reproduce the behavior

idoitcli init 

### Environment

OS: Fedora 29

| Question                  | Answer            |
| ------------------------- | ----------------- |
| `idoitcli` version        | 0.5             |
| PHP version               | 7.2.11           |
| i-doit version            | 1.11.1 pro    |
| i-doit API add-on version |1.9.1             |

**Comment by bheisig** [comment]
This issue is fixed in [version 0.6](https://github.com/bheisig/i-doit-cli/releases/tag/0.6).
