### ISSUE TITLE
Not possible to set memory capacity

### ISSUE THREAD

**Issue by fourti** [bheisig/i-doit-cli#25]
In version 0.7 it's not possible to set the capacity of memory of a virtual server:

idoitcli save virtual\ server/myserver.example.com/memory
Create/update CMDB objects and their category entries

[Memory] Title?
[Memory] Manufacturer?
[Memory] Type?
[Memory] Memory unit?
[Memory] Description?

Setting a Memory unit of "8 GB" is not possible also.

What am I missing?

**Comment by bheisig** [comment]
Thanks for your request. To fully understand what's going on there's [an issue template](https://raw.githubusercontent.com/bheisig/i-doit-cli/master/docs/issue_template.md) I like you to fill out completely.

**Comment by fourti** [comment]
I tried to save the capacity with a yaml file which is parsed with yq/jq and then idoitcli is called :

idoitcli save '$objType/$objInstance/$attributeCategory' $attrs

Virtual server:
  myserver.example.com:
    Memory:
      Quantity: 1
      Title: 1
      Type: 1
      Capacity: 8
      Unit: GB

The Capacity is never saved. Just the Unit is in the DB. In the API-Log is no occurence of capacity.

Even the interactive mode doesn't ask for capacity:

### Expected behavior



idoitcli save virtual\ server/myserver.example.com/memory
Create/update CMDB objects and their category entries

[Memory] Title?
[Memory] Manufacturer?
[Memory] Type?
[Memory] Memory unit?
[Memory] Description?
[Memory] Capacity?
Nothing to do
### Actual behavior

idoitcli save virtual\ server/myserver.example.com/memory
Create/update CMDB objects and their category entries

[Memory] Title?
[Memory] Manufacturer?
[Memory] Type?
[Memory] Memory unit?
[Memory] Description?
Nothing to do

### Steps to reproduce the behavior

idoitcli save virtual\ server/myserver.example.com/memory


### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| `idoitcli` version        | 0.7            |
| PHP version               | 7.2.14             |
| i-doit version            | 1.12.1 PRO    |
| i-doit API add-on version | 1.10.1             |


### Server logs

Excerpt taken from `/var/www/html/i-doit/log/api_*.log`:

[2019-02-19 16:36:43 702224] DEBUG: i-doit JSON-RPC API v1.10.1
 - i-doit 1.12.1 PRO
[2019-02-19 16:36:43 702264] DEBUG: Provided raw request:
{
    "version": "2.0",
    "method": "cmdb.category.save",
    "params": {
        "object": 59,
        "data": {
            "title": 1,
            "type": 1,
            "unit": "GB"
        },
        "category": "C__CATG__MEMORY",
        "apikey": "...",
        "language": "en"
    },
    "id": 3
}

**Comment by bheisig** [comment]
Hello,

Sorry for the late reply. This issue is finally fixed. The fix will be included in the upcoming release. Thanks again for your feedback!
